/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apotek;

import javax.swing.JOptionPane;

/**
 *
 * @author fahri
 */
public class menu_kasir extends javax.swing.JFrame {

    /**
     * Creates new form menu_kasir
     */
    public menu_kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        main_menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnHome = new javax.swing.JButton();
        BtnCashier = new javax.swing.JButton();
        BtnStore = new javax.swing.JButton();
        BtnLogout1 = new javax.swing.JButton();
        sub_menu = new javax.swing.JPanel();
        MenuHome = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        MenuCashier = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kasir = new javax.swing.JTable();
        kolom_harga = new javax.swing.JTextField();
        kolom_jumlah = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        uang_bayar = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        tombol_tambah = new javax.swing.JButton();
        tombol_hapus = new javax.swing.JButton();
        tombol_ubah = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        kolom_barang = new javax.swing.JTextField();
        kolom_id = new javax.swing.JTextField();
        MenuStore = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg footer header.png"))); // NOI18N

        main_menu.setBackground(new java.awt.Color(64, 175, 134));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" MY - APOTEK");

        BtnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnHome.setForeground(new java.awt.Color(0, 153, 51));
        BtnHome.setText("HOME");
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        BtnCashier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnCashier.setForeground(new java.awt.Color(0, 153, 51));
        BtnCashier.setText("CASHIER");
        BtnCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCashierActionPerformed(evt);
            }
        });

        BtnStore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnStore.setForeground(new java.awt.Color(0, 153, 51));
        BtnStore.setText("STORE");
        BtnStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStoreActionPerformed(evt);
            }
        });

        BtnLogout1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnLogout1.setForeground(new java.awt.Color(0, 153, 51));
        BtnLogout1.setText("LOGOUT");
        BtnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_menuLayout = new javax.swing.GroupLayout(main_menu);
        main_menu.setLayout(main_menuLayout);
        main_menuLayout.setHorizontalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnStore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(main_menuLayout.createSequentialGroup()
                        .addComponent(BtnLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        main_menuLayout.setVerticalGroup(
            main_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_menuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(BtnHome)
                .addGap(18, 18, 18)
                .addComponent(BtnCashier)
                .addGap(18, 18, 18)
                .addComponent(BtnStore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnLogout1)
                .addContainerGap())
        );

        sub_menu.setLayout(new java.awt.CardLayout());

        MenuHome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HOME.png"))); // NOI18N

        javax.swing.GroupLayout MenuHomeLayout = new javax.swing.GroupLayout(MenuHome);
        MenuHome.setLayout(MenuHomeLayout);
        MenuHomeLayout.setHorizontalGroup(
            MenuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuHomeLayout.setVerticalGroup(
            MenuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sub_menu.add(MenuHome, "card2");

        MenuCashier.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 102));
        jLabel6.setText("CASHIER");

        jLabel3.setText("ID BARANG             :");

        jLabel4.setText("HARGA BARANG    :");

        jLabel5.setText("JUMLAH BARANG  :");

        tabel_kasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Barang", "Harga ", "Jumlah ", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel_kasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kasirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_kasir);

        kolom_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolom_jumlahActionPerformed(evt);
            }
        });

        jLabel12.setText("TOTAL                 :");

        jLabel13.setText("UANG BAYAR     :");

        jLabel14.setText("KEMBALIAN        :");

        tombol_tambah.setBackground(new java.awt.Color(64, 175, 134));
        tombol_tambah.setForeground(new java.awt.Color(255, 255, 255));
        tombol_tambah.setText("TAMBAH");
        tombol_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_tambahActionPerformed(evt);
            }
        });

        tombol_hapus.setBackground(new java.awt.Color(64, 175, 134));
        tombol_hapus.setForeground(new java.awt.Color(255, 255, 255));
        tombol_hapus.setText("HAPUS");

        tombol_ubah.setBackground(new java.awt.Color(64, 175, 134));
        tombol_ubah.setForeground(new java.awt.Color(255, 255, 255));
        tombol_ubah.setText("SELESAI");
        tombol_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol_ubahActionPerformed(evt);
            }
        });

        jLabel7.setText("NAMA BARANG     :");

        kolom_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolom_barangActionPerformed(evt);
            }
        });

        kolom_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolom_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuCashierLayout = new javax.swing.GroupLayout(MenuCashier);
        MenuCashier.setLayout(MenuCashierLayout);
        MenuCashierLayout.setHorizontalGroup(
            MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCashierLayout.createSequentialGroup()
                .addGroup(MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuCashierLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel6))
                    .addGroup(MenuCashierLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(kolom_id, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuCashierLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(kolom_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(uang_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuCashierLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuCashierLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(kolom_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuCashierLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kolom_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(tombol_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tombol_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tombol_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        MenuCashierLayout.setVerticalGroup(
            MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuCashierLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kolom_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuCashierLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kolom_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uang_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kolom_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kolom_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tombol_ubah)
                        .addComponent(tombol_hapus)
                        .addComponent(tombol_tambah)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        sub_menu.add(MenuCashier, "card3");

        MenuStore.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8.setText("STORE");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout MenuStoreLayout = new javax.swing.GroupLayout(MenuStore);
        MenuStore.setLayout(MenuStoreLayout);
        MenuStoreLayout.setHorizontalGroup(
            MenuStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuStoreLayout.createSequentialGroup()
                .addGroup(MenuStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuStoreLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel8))
                    .addGroup(MenuStoreLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        MenuStoreLayout.setVerticalGroup(
            MenuStoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuStoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        sub_menu.add(MenuStore, "card4");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sub_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(main_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sub_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        // TODO add your handling code here:
        sub_menu.removeAll();
        sub_menu.repaint();
        sub_menu.revalidate();

        //add panel
        sub_menu.add(MenuHome);
        sub_menu.repaint();
        sub_menu.revalidate();
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCashierActionPerformed
        // TODO add your handling code here:
        sub_menu.removeAll();
        sub_menu.repaint();
        sub_menu.revalidate();

        //add panel
        sub_menu.add(MenuCashier);
        sub_menu.repaint();
        sub_menu.revalidate();
    }//GEN-LAST:event_BtnCashierActionPerformed

    private void BtnStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStoreActionPerformed
        // TODO add your handling code here:
        sub_menu.removeAll();
        sub_menu.repaint();
        sub_menu.revalidate();

        //add panel
        sub_menu.add(MenuStore);
        sub_menu.repaint();
        sub_menu.revalidate();
    }//GEN-LAST:event_BtnStoreActionPerformed

    private void BtnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogout1ActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Keluar ?","Perhatian",JOptionPane.YES_NO_OPTION);
        if (option == 0){
            //true condition
            Login A = new Login();
            A.setVisible(true);
            this.setVisible(false);
        } else {

        }
    }//GEN-LAST:event_BtnLogout1ActionPerformed

    private void tabel_kasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kasirMouseClicked
        // TODO add your handling code here:
        // Menampilkan pada kolom yang di isi pada saat tabel di klik
        int baris = tabel_kasir .rowAtPoint(evt.getPoint()); //evt itu parameter diatasnya jadi ikut aja

        String id = tabel_kasir.getValueAt(baris, 1).toString();
        //taro nilai yg di klik di textfield (ID)
        kolom_id.setText(id);

        //get ID
        String harga = tabel_kasir.getValueAt(baris, 2).toString();
        //taro nilai yg di klik di textfield (ID)
        kolom_harga.setText(harga);

        //get nama
        String jumlah = tabel_kasir.getValueAt(baris, 3).toString();
        //taro nilai yg di klik di textfield (inputan nama)
        kolom_jumlah.setText(jumlah);
    }//GEN-LAST:event_tabel_kasirMouseClicked

    private void kolom_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolom_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolom_jumlahActionPerformed

    private void tombol_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_tambahActionPerformed
        // TODO add your handling code here:
        
        /*String id = kolom_id.getText();
        String harga = kolom_harga.getText();
        String jumlah = kolom_jumlah.getText();

        // if else ini biar data belum ke input ga bisa klik 'tambah'
        if (id.equals("")){
            JOptionPane.showMessageDialog(null,"Isi pilihan Terlebih Dahulu");
        }else if(harga.equals("")){
            JOptionPane.showMessageDialog(null,"Isi harga Terlebih Dahulu");
        }else if (jumlah.equals("")){
            JOptionPane.showMessageDialog(null,"Isi jumlah Terlebih Dahulu");
        }else{
            try {
                String Q = "Insert into kasir (nama_barang,harga,jumlah) Values ('"+id+"','"+harga+"','"+jumlah+"')";
                java.sql.Connection Vconn = (Connection)KoneksiDB.konfigDB(); //memanggil fungsi koneksi database
                java.sql.PreparedStatement s = Vconn.prepareStatement(Q); //mengirimkan parameter
                s.execute(); //eksekusi sql
                JOptionPane.showMessageDialog(null,"Tambah Data Berhasi");
            }catch (Exception e){
                JOptionPane.showMessageDialog(null,"Tambah Data Gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            tampil_table(); //agar membuat data otomatis ke reload, panggil tampil table di action ini
            bersih(); // agar setelah klik dan berhasil inputannya text inputan kosong seperti semula lagi
        }*/
    }//GEN-LAST:event_tombol_tambahActionPerformed

    private void tombol_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_ubahActionPerformed
        // TODO add your handling code here:
        /*String id = kolom_id.getText();
        String harga = kolom_harga.getText();
        String jumlah = kolom_jumlah.getText();

        // if else ini biar belum input apa2 ga bisa klik 'ubah'
        if (id.equals("")){
            JOptionPane.showMessageDialog(null,"Isi pilihan Terlebih Dahulu");
        }else if(harga.equals("")){
            JOptionPane.showMessageDialog(null,"Isi harga Terlebih Dahulu");
        }else if (jumlah.equals("")){
            JOptionPane.showMessageDialog(null,"Isi jumlah Terlebih Dahulu");
        }else{
            try {
                String Vsql = "UPDATE karyawan SET nama_barang = '"+id+"', id_barang = '"+harga+"', jumlah = '"+jumlah+"' WHERE nama_barang = '"+id+"'";
                java.sql.Connection Vconn = (Connection)KoneksiDB.konfigDB(); //memanggil fungsi koneksi di kelas lainnya
                java.sql.PreparedStatement pst = Vconn.prepareStatement(Vsql); //mengirimkan parameter ke fungsi java sql
                pst.execute(); //execute sql
                JOptionPane.showMessageDialog(null, "Ubah data berhasil");
                tampil_table();
                bersih();
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Ubah data gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }*/
    }//GEN-LAST:event_tombol_ubahActionPerformed

    private void kolom_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolom_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolom_barangActionPerformed

    private void kolom_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolom_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolom_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_store().setVisible(true);
            }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCashier;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnLogout1;
    private javax.swing.JButton BtnStore;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel MenuCashier;
    private javax.swing.JPanel MenuHome;
    private javax.swing.JPanel MenuStore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField kolom_barang;
    private javax.swing.JTextField kolom_harga;
    private javax.swing.JTextField kolom_id;
    private javax.swing.JTextField kolom_jumlah;
    private javax.swing.JPanel main_menu;
    private javax.swing.JPanel sub_menu;
    private javax.swing.JTable tabel_kasir;
    private javax.swing.JButton tombol_hapus;
    private javax.swing.JButton tombol_tambah;
    private javax.swing.JButton tombol_ubah;
    private javax.swing.JTextField total;
    private javax.swing.JTextField uang_bayar;
    // End of variables declaration//GEN-END:variables
}
